# Generated by Django 4.0.3 on 2022-03-09 09:23

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateut', models.CharField(max_length=50)),
                ('type_of_dis', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('criteria', models.CharField(max_length=30)),
                ('typeofbenefit', models.CharField(max_length=30)),
                ('documents', models.FileField(upload_to=pages.models.upload_to)),
            ],
        ),
    ]
